# Generated by Django 2.0.7 on 2018-07-24 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('serial_num', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='光谱仪序列号')),
                ('install_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='安装日期')),
                ('installer', models.CharField(default='无', max_length=10, verbose_name='安装人')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测试完成日期')),
                ('tester', models.CharField(default='无', max_length=10, verbose_name='测试完成人')),
                ('changed_device', models.CharField(default='无', max_length=50, verbose_name='更换器件(可能多次更改)')),
                ('changed_device_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更换时间')),
                ('errs', models.CharField(default='无', max_length=500, verbose_name='出现过的问题')),
                ('holder', models.CharField(default='无', max_length=50, verbose_name='持有人')),
                ('destination', models.CharField(default='无', max_length=50, verbose_name='光谱仪的去向')),
            ],
        ),
    ]
