# Generated by Django 2.0.7 on 2018-07-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '光谱仪二维码信息', 'verbose_name_plural': '光谱仪二维码信息'},
        ),
    ]
